#!/usr/bin/env bash
# This file is generated by bin/build from src/*.sh. Do not edit directly.

if [ -n "${_BASHSTOCK_LOADED:-}" ]; then
  return 0
fi
_BASHSTOCK_LOADED=1

if [ -z "${BASHSTOCK_ROOT:-}" ]; then
  BASHSTOCK_ROOT="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
fi


# Product identity values.
# shellcheck disable=SC2034
readonly BASHSTOCK_NAME='bashstock'
# shellcheck disable=SC2034
readonly BASHSTOCK_VERSION='1.0.0'


### Write one command-prefixed diagnostic to standard error.
console::_write-error() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  printf '%s: %s\n' "${BASHSTOCK_NAME:-bashstock}" "$1" >&2
}

# shellcheck disable=SC2234

### Test whether a value is an unsigned decimal integer.
number::_is-non-negative-integer() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  ( [[ "$1" =~ ^[0-9]+$ ]] )
}

### Test whether a value is a positive unsigned decimal integer.
number::_is-positive-integer() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  ( [[ "$1" =~ ^[1-9][0-9]*$ ]] )
}

### Test whether an unsigned decimal integer does not exceed a maximum.
number::_is-non-negative-integer-at-most() {
  if [[ "$#" -ne 2 ]] ||
    ! number::_is-non-negative-integer "$1" ||
    ! number::_is-positive-integer "$2"; then
    return 64
  fi

  local value="$1"
  local maximum="$2"
  local LC_ALL=C

  while [[ "${#value}" -gt 1 && "${value:0:1}" == '0' ]]; do
    value="${value:1}"
  done
  if [[ "${#value}" -lt "${#maximum}" ]]; then
    return 0
  fi
  if [[ "${#value}" -gt "${#maximum}" || "${value}" > "${maximum}" ]]; then
    return 1
  fi
  return 0
}

### Test whether a positive decimal integer does not exceed a maximum.
number::_is-positive-integer-at-most() {
  if [[ "$#" -ne 2 ]] || ! number::_is-positive-integer "$1"; then
    return 64
  fi

  number::_is-non-negative-integer-at-most "$1" "$2"
}

### Test whether a value is a signed or unsigned decimal integer.
number::is-integer() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  ( [[ "$1" =~ ^[+-]?[0-9]+$ ]] )
}

### Test whether a value is a signed or unsigned decimal fraction.
number::is-decimal() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  ( [[ "$1" =~ ^[+-]?([0-9]+\.[0-9]*|\.[0-9]+)$ ]] )
}

### Test whether a value is a decimal integer or fraction.
number::is-number() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  ( [[ "$1" =~ ^[+-]?([0-9]+|[0-9]+\.[0-9]*|\.[0-9]+)$ ]] )
}

# shellcheck disable=SC2119,SC2120,SC2233,SC2234

### Require one argument that contains no newline.
string::_require-one-line() {
  if [[ "$#" -ne 1 || "$1" == *$'\n'* ]]; then
    return 64
  fi
}

### Require one non-empty argument that contains no newline.
string::_require-non-empty-line() {
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    return 64
  fi

  string::_require-one-line "$1"
}

### Require the current locale to use UTF-8.
string::_require-utf8-locale() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  if ! command -v locale >/dev/null 2>&1; then
    console::_write-error 'A UTF-8 locale is required.'
    return 69
  fi

  local character_map=''
  character_map="$(locale charmap 2>/dev/null)" || {
    console::_write-error 'A UTF-8 locale is required.'
    return 69
  }
  case "${character_map}" in
    UTF-8 | UTF8 | utf-8 | utf8)
      return 0
      ;;
    *)
      console::_write-error 'A UTF-8 locale is required.'
      return 69
      ;;
  esac
}

### Remove leading and trailing whitespace.
string::trim() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local value="$1"
  local first=''
  local last=''

  while [[ -n "${value}" ]]; do
    first="${value:0:1}"
    if [[ "${first}" != [[:space:]] ]]; then
      break
    fi
    value="${value:1}"
  done

  while [[ -n "${value}" ]]; do
    last="${value:$((${#value} - 1)):1}"
    if [[ "${last}" != [[:space:]] ]]; then
      break
    fi
    value="${value:0:$((${#value} - 1))}"
  done

  printf '%s\n' "${value}"
}

### Trim whitespace and collapse each interior run to one ASCII space.
string::collapse-whitespace() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local value="$1"
  local result=''
  local character=''
  local whitespace='1'
  local index=''

  for ((index = 0; index < ${#value}; index++)); do
    character="${value:index:1}"
    if [[ "${character}" == [[:space:]] ]]; then
      whitespace='1'
    else
      if [[ "${whitespace}" -eq 1 && -n "${result}" ]]; then
        result+=' '
      fi
      result+="${character}"
      whitespace='0'
    fi
  done

  printf '%s\n' "${result}"
}

### Split a value by a non-empty literal delimiter and preserve empty fields.
string::split() {
  if [[ "$#" -ne 2 || -z "$2" ]] ||
    ! string::_require-one-line "$1" ||
    ! string::_require-one-line "$2"; then
    return 64
  fi

  local value="$1"
  local delimiter="$2"
  local part=''

  while [[ "${value}" == *"${delimiter}"* ]]; do
    part="${value%%"${delimiter}"*}"
    printf '%s\n' "${part}"
    value="${value#*"${delimiter}"}"
  done
  printf '%s\n' "${value}"
}

### Translate ASCII letter case according to the requested mode.
string::_translate-ascii() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local value="$1"
  local mode="$2"
  local upper='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  local lower='abcdefghijklmnopqrstuvwxyz'
  local character=''
  local prefix=''
  local index=''
  local result=''
  local position=''
  local LC_ALL=C

  for ((position = 0; position < ${#value}; position++)); do
    character="${value:position:1}"
    case "${mode}:${character}" in
      lower:[A-Z])
        prefix="${upper%%"${character}"*}"
        index="${#prefix}"
        result+="${lower:index:1}"
        ;;
      upper:[a-z])
        prefix="${lower%%"${character}"*}"
        index="${#prefix}"
        result+="${upper:index:1}"
        ;;
      swap:[A-Z])
        prefix="${upper%%"${character}"*}"
        index="${#prefix}"
        result+="${lower:index:1}"
        ;;
      swap:[a-z])
        prefix="${lower%%"${character}"*}"
        index="${#prefix}"
        result+="${upper:index:1}"
        ;;
      *)
        result+="${character}"
        ;;
    esac
  done

  printf '%s\n' "${result}"
}

### Convert ASCII uppercase letters to lowercase.
string::lower() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  string::_translate-ascii "$1" lower
}

### Convert ASCII lowercase letters to uppercase.
string::upper() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  string::_translate-ascii "$1" upper
}

### Swap the case of every ASCII letter.
string::swap-case() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  string::_translate-ascii "$1" swap
}

### Convert the first ASCII letter to lowercase when applicable.
string::lower-first() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  if [[ -z "$1" ]]; then
    printf '\n'
    return 0
  fi

  local first=''
  first="$(string::lower "${1:0:1}")" || return "$?"
  printf '%s%s\n' "${first}" "${1:1}"
}

### Convert the first ASCII letter to uppercase when applicable.
string::upper-first() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  if [[ -z "$1" ]]; then
    printf '\n'
    return 0
  fi

  local first=''
  first="$(string::upper "${1:0:1}")" || return "$?"
  printf '%s%s\n' "${first}" "${1:1}"
}

### Remove one matching pair of surrounding single or double quotes.
string::strip-surrounding-quotes() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local value="$1"
  if [[ "${#value}" -ge 2 ]]; then
    if [[ "${value:0:1}" == "'" && "${value:$((${#value} - 1)):1}" == "'" ]] ||
      [[ "${value:0:1}" == '"' && "${value:$((${#value} - 1)):1}" == '"' ]]; then
      value="${value:1:$((${#value} - 2))}"
    fi
  fi
  printf '%s\n' "${value}"
}

### Remove every substring that matches a Bash pattern.
string::remove-all-matches() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${1//$2/}"
}

### Remove the first substring that matches a Bash pattern.
string::remove-first-match() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${1/$2/}"
}

### Remove the longest prefix that matches a Bash pattern.
string::remove-prefix() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${1##$2}"
}

### Remove the longest suffix that matches a Bash pattern.
string::remove-suffix() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${1%%$2}"
}

### Percent-encode a UTF-8 string byte by byte.
string::encode-url() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local value="$1"
  local character=''
  local encoded=''
  local hex=''
  local code=''
  local index=''
  local LC_ALL=C

  for ((index = 0; index < ${#value}; index++)); do
    character="${value:index:1}"
    case "${character}" in
      [a-zA-Z0-9.~_-])
        encoded+="${character}"
        ;;
      *)
        printf -v code '%d' "'${character}"
        code="$((code & 255))"
        printf -v hex '%02X' "${code}"
        encoded+="%${hex}"
        ;;
    esac
  done

  printf '%s\n' "${encoded}"
}

### Decode percent-encoded bytes without translating plus signs.
string::decode-url() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local value="$1"
  local decoded=''
  local byte=''
  local hex=''
  local index='0'
  local LC_ALL=C

  while ((index < ${#value})); do
    if [[ "${value:index:1}" == '%' ]]; then
      if ((index + 2 >= ${#value})); then
        return 64
      fi
      hex="${value:index+1:2}"
      if ! ( [[ "${hex}" =~ ^[0-9A-Fa-f]{2}$ ]] ) || [[ "${hex}" == '00' ]]; then
        return 64
      fi
      printf -v byte '%b' "\\x${hex}"
      decoded+="${byte}"
      index=$((index + 3))
    else
      decoded+="${value:index:1}"
      index=$((index + 1))
    fi
  done

  printf '%s\n' "${decoded}"
}

### Test whether a value contains a literal substring.
string::contains() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  [[ "$1" == *"$2"* ]]
}

### Test whether a value starts with a literal prefix.
string::starts-with() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  [[ "${1:0:${#2}}" == "$2" ]]
}

### Test whether a value ends with a literal suffix.
string::ends-with() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  if [[ -z "$2" ]]; then
    return 0
  fi
  if [[ "${#2}" -gt "${#1}" ]]; then
    return 1
  fi
  [[ "${1:$((${#1} - ${#2}))}" == "$2" ]]
}

### Join values with a literal delimiter.
string::join() {
  if [[ "$#" -lt 1 ]]; then
    return 64
  fi

  local delimiter="$1"
  local value=''
  local first='1'
  shift

  for value in "$@"; do
    if [[ "${first}" -eq 0 ]]; then
      printf '%s' "${delimiter}"
    fi
    printf '%s' "${value}"
    first='0'
  done
  printf '\n'
}

### Write the byte length of a value.
string::byte-length() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  local LC_ALL=C
  printf '%s\n' "${#1}"
}

### Write the character length of a value in a UTF-8 locale.
string::length() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  string::_require-utf8-locale || return "$?"
  printf '%s\n' "${#1}"
}

### Replace the first substring that matches a Bash pattern.
string::replace-first() {
  if [[ "$#" -ne 3 || -z "$2" ]]; then
    return 64
  fi
  local value="$1"
  local pattern="$2"
  local replacement="$3"
  if shopt -q patsub_replacement 2>/dev/null; then
    replacement="${replacement//\\/\\\\}"
    replacement="${replacement//&/\\&}"
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${value/$pattern/$replacement}"
}

### Replace every substring that matches a Bash pattern.
string::replace-all() {
  if [[ "$#" -ne 3 || -z "$2" ]]; then
    return 64
  fi
  local value="$1"
  local pattern="$2"
  local replacement="$3"
  if shopt -q patsub_replacement 2>/dev/null; then
    replacement="${replacement//\\/\\\\}"
    replacement="${replacement//&/\\&}"
  fi
  # shellcheck disable=SC2295
  printf '%s\n' "${value//$pattern/$replacement}"
}

### Replace the rightmost non-empty substring that matches a Bash pattern.
string::replace-last() {
  if [[ "$#" -ne 3 || -z "$2" ]]; then
    return 64
  fi

  local value="$1"
  local pattern="$2"
  local replacement="$3"
  local candidate=''
  local matched=''
  local start=''
  local length=''

  for ((start = ${#value} - 1; start >= 0; start--)); do
    candidate="${value:start}"
    for ((length = ${#candidate}; length >= 1; length--)); do
      matched="${candidate:0:length}"
      # shellcheck disable=SC2053
      if [[ "${matched}" == ${pattern} ]]; then
        printf '%s%s%s\n' \
          "${value:0:start}" \
          "${replacement}" \
          "${candidate:length}"
        return 0
      fi
    done
  done

  printf '%s\n' "${value}"
}

### Require a named value to be non-empty.
string::require-non-empty() {
  if [[ "$#" -ne 2 ]] || ! string::_require-non-empty-line "$1"; then
    return 64
  fi
  if [[ -n "$2" ]]; then
    return 0
  fi
  console::_write-error "$1 must not be empty."
  return 64
}

### Require a named value to be empty.
string::require-empty() {
  if [[ "$#" -ne 2 ]] || ! string::_require-non-empty-line "$1"; then
    return 64
  fi
  if [[ -z "$2" ]]; then
    return 0
  fi
  console::_write-error "$1 must be empty."
  return 64
}

### Require a named value to equal one of the allowed values.
string::require-allowed() {
  if [[ "$#" -lt 3 ]] || ! string::_require-non-empty-line "$1"; then
    return 64
  fi

  local name="$1"
  local value="$2"
  local allowed=''
  shift 2

  for allowed in "$@"; do
    if [[ "${value}" == "${allowed}" ]]; then
      return 0
    fi
  done

  console::_write-error "${name} has an unsupported value."
  return 64
}

### Write a validated character range from a UTF-8 string.
string::slice() {
  if [[ "$#" -lt 2 || "$#" -gt 3 ]] ||
    ! number::_is-non-negative-integer-at-most "$2" 2147483647; then
    return 64
  fi
  string::_require-utf8-locale || return "$?"

  local value="$1"
  local start="$2"
  local end="${3-${#1}}"
  local length="${#value}"

  if ! number::_is-non-negative-integer-at-most "${end}" 2147483647; then
    return 64
  fi
  if ((10#${start} > 10#${end} || 10#${end} > length)); then
    return 64
  fi
  printf '%s\n' "${value:10#${start}:10#${end}-10#${start}}"
}


### Test a value against a Bash POSIX extended regular expression.
regex::is-match() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local value="$1"
  local expression="$2"
  local status=''

  # shellcheck disable=SC2233
  if ( [[ "${value}" =~ ${expression} ]] ); then
    return 0
  else
    status="$?"
  fi

  if [[ "${status}" -eq 2 ]]; then
    return 64
  fi
  return 1
}

### Write one capture group from a Bash POSIX extended regular expression.
regex::capture-group() {
  if [[ "$#" -ne 3 ]] ||
    ! number::_is-non-negative-integer-at-most "$3" 2147483647; then
    return 64
  fi

  local value="$1"
  local expression="$2"
  local group="$((10#$3))"

  (
    local status=''
    if [[ "${value}" =~ ${expression} ]]; then
      if ((group >= ${#BASH_REMATCH[@]})); then
        return 64
      fi
      if ! string::_require-one-line "${BASH_REMATCH[group]}"; then
        return 64
      fi
      printf '%s\n' "${BASH_REMATCH[group]}"
      return 0
    else
      # shellcheck disable=SC2319
      status="$?"
    fi
    if [[ "${status}" -eq 2 ]]; then
      return 64
    fi
    return 1
  )
}

### Write all capture groups from a Bash POSIX extended regular expression.
regex::capture-groups() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local value="$1"
  local expression="$2"

  (
    local status=''
    local index=''
    if [[ "${value}" =~ ${expression} ]]; then
      for ((index = 1; index < ${#BASH_REMATCH[@]}; index++)); do
        if ! string::_require-one-line "${BASH_REMATCH[index]}"; then
          return 64
        fi
        printf '%s\n' "${BASH_REMATCH[index]}"
      done
      return 0
    else
      # shellcheck disable=SC2319
      status="$?"
    fi
    if [[ "${status}" -eq 2 ]]; then
      return 64
    fi
    return 1
  )
}


### Test whether the remaining arguments contain the expected value.
array::contains() {
  if [[ "$#" -lt 1 ]]; then
    return 64
  fi

  local expected="$1"
  local value=''
  shift

  for value in "$@"; do
    if [[ "${value}" == "${expected}" ]]; then
      return 0
    fi
  done

  return 1
}

### Write the arguments in reverse order, one value per line.
array::reverse() {
  local values=("$@")
  local index=''

  for ((index = ${#values[@]} - 1; index >= 0; index--)); do
    if ! string::_require-one-line "${values[index]}"; then
      return 64
    fi
    printf '%s\n' "${values[index]}"
  done
}

### Write the number of arguments.
array::length() {
  printf '%s\n' "$#"
}

### Write the first argument when one is available.
array::first() {
  if [[ "$#" -eq 0 ]]; then
    return 1
  fi
  if ! string::_require-one-line "$1"; then
    return 64
  fi

  printf '%s\n' "$1"
}

### Write the last argument when one is available.
array::last() {
  if [[ "$#" -eq 0 ]]; then
    return 1
  fi

  local value=''
  for value in "$@"; do
    :
  done

  if ! string::_require-one-line "${value}"; then
    return 64
  fi
  printf '%s\n' "${value}"
}

### Write each distinct argument once in its original order.
array::unique() {
  local seen=()
  local value=''
  local previous=''
  local duplicate='0'

  for value in "$@"; do
    if ! string::_require-one-line "${value}"; then
      return 64
    fi

    duplicate='0'
    for previous in "${seen[@]}"; do
      if [[ "${previous}" == "${value}" ]]; then
        duplicate='1'
        break
      fi
    done

    if [[ "${duplicate}" -eq 0 ]]; then
      seen[${#seen[@]}]="${value}"
      printf '%s\n' "${value}"
    fi
  done
}

### Prefix every value and write one result per line.
array::prepend-to-each() {
  if [[ "$#" -lt 1 ]] || ! string::_require-one-line "$1"; then
    return 64
  fi

  local prefix="$1"
  local value=''
  shift

  for value in "$@"; do
    if ! string::_require-one-line "${value}"; then
      return 64
    fi
    printf '%s%s\n' "${prefix}" "${value}"
  done
}


### Require a value to follow the current named argument.
arg::require-next() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local remaining="$1"
  local option="$2"

  if [[ "${remaining}" -lt 2 ]]; then
    console::_write-error "Option ${option} requires a value."
    return 64
  fi
}

### Require a named argument to have a non-empty value.
arg::require() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local name="$1"
  local value="$2"

  if [[ -z "${value}" ]]; then
    console::_write-error "Option ${name} is required."
    return 64
  fi
}

### Require a named argument value to be a decimal integer.
arg::integer() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local name="$1"
  local value="$2"

  if ! number::is-integer "${value}"; then
    console::_write-error "Option ${name} must be an integer: ${value}"
    return 64
  fi
}

### Require a named argument value to match one candidate.
arg::one-of() {
  if [[ "$#" -lt 3 ]]; then
    return 64
  fi

  local name="$1"
  local value="$2"
  local candidate=''
  shift 2

  for candidate in "$@"; do
    if [[ "${value}" == "${candidate}" ]]; then
      return 0
    fi
  done

  console::_write-error "Option ${name} must be one of: $*. Got: ${value}"
  return 64
}

### Report a named argument that no case branch recognized.
arg::unknown() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  console::_write-error "Unknown option: $1"
  return 64
}


### Write the completion helper name that corresponds to a public function.
arg::completion::_helper-name() {
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    return 64
  fi

  local target="$1"
  local namespace="${target%::*}"
  local action="${target##*::}"

  if [[ "${namespace}" == "${target}" || -z "${action}" ]]; then
    return 64
  fi
  printf '%s::_%s-args\n' "${namespace}" "${action}"
}

### Write the public function name that corresponds to a completion helper.
arg::completion::_target-name() {
  if [[ "$#" -ne 1 || "$1" != *'::_'*'-args' ]]; then
    return 64
  fi

  local helper="${1%-args}"
  local namespace="${helper%::_*}"
  local action="${helper##*::_}"

  printf '%s::%s\n' "${namespace}" "${action}"
}

### Dispatch Tab completion to the target function's completion helper.
###
### Registered with `complete -F` for every function that has a matching
### `::_<action>-args` helper. Bash calls this with no arguments and reads
### COMP_WORDS, COMP_CWORD, and COMPREPLY.
arg::completion::dispatch() {
  local target="${COMP_WORDS[0]}"
  local current="${COMP_WORDS[COMP_CWORD]}"
  local previous=''
  local helper=''
  local candidates=''

  helper="$(arg::completion::_helper-name "${target}")" || return 0
  declare -F "${helper}" >/dev/null 2>&1 || return 0

  if [[ "${COMP_CWORD}" -gt 0 ]]; then
    previous="${COMP_WORDS[COMP_CWORD - 1]}"
  fi

  if [[ "${previous}" == -* ]]; then
    candidates="$("${helper}" "${previous}")"
  else
    candidates="$("${helper}")"
  fi

  # shellcheck disable=SC2207
  COMPREPLY=($(compgen -W "${candidates}" -- "${current}"))
}

### Register Tab completion for every function that has a completion helper.
###
### Called once after every module has been loaded, so that functions
### defined later in the load order are still discovered.
arg::completion::register-all() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  type complete >/dev/null 2>&1 || return 0

  local name=''
  local target=''

  while IFS= read -r name; do
    target="$(arg::completion::_target-name "${name}")" || continue
    declare -F "${target}" >/dev/null 2>&1 || continue
    complete -F arg::completion::dispatch "${target}"
  done < <(declare -F | awk '{print $3}' | grep -E '::_[a-z][a-z0-9-]*-args$')
}


### Write the normalized operating-system family.
system::operating-system() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  case "${OSTYPE:-}" in
    darwin*)
      printf 'darwin\n'
      ;;
    linux*)
      printf 'linux\n'
      ;;
    *)
      printf 'unknown\n'
      ;;
  esac
}

### Write the current host name.
system::host-name() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  if [[ -n "${HOSTNAME:-}" ]]; then
    printf '%s\n' "${HOSTNAME}"
    return 0
  fi

  local value=''
  if ! command -v hostname >/dev/null 2>&1; then
    return 1
  fi
  if ! value="$(hostname 2>/dev/null)" || [[ -z "${value}" ]]; then
    return 1
  fi
  printf '%s\n' "${value}"
}


### Test whether a command name resolves in the current environment.
command::exists() {
  if [[ "$#" -ne 1 || -z "$1" || "$1" == -* ]] ||
    ! string::_require-one-line "$1"; then
    return 64
  fi

  command -v "$1" >/dev/null 2>&1
}

### Require a command name to resolve in the current environment.
command::require() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  if command::exists "$1"; then
    return 0
  fi

  local status="$?"
  if [[ "${status}" -eq 64 ]]; then
    return 64
  fi

  console::_write-error "Required command is unavailable: $1"
  return 69
}

### Run a command directly as root or through validated sudo access.
command::run-as-root() {
  if [[ "$#" -lt 1 || -z "$1" ]]; then
    return 64
  fi

  if [[ "${EUID}" -eq 0 ]]; then
    command "$@"
    return "$?"
  fi

  if ! command -v sudo >/dev/null 2>&1; then
    console::_write-error 'sudo is required for this operation.'
    return 69
  fi

  if ! sudo -v; then
    return 77
  fi
  sudo -- "$@"
}


### Test whether a shell function is defined.
shell::is-function-defined() {
  if [[ "$#" -ne 1 || -z "$1" || "$1" == -* ]] ||
    ! string::_require-one-line "$1"; then
    return 64
  fi

  declare -F "$1" >/dev/null 2>&1
}


### Test whether the controlling terminal is readable and writable.
terminal::is-available() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  [[ -c /dev/tty && -r /dev/tty && -w /dev/tty ]]
}


### Write the lexical directory portion of a path.
path::directory-name() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local path="$1"
  if [[ -z "${path}" ]]; then
    printf '.\n'
    return 0
  fi

  while [[ "${path}" != '/' && "${path}" == */ ]]; do
    path="${path%/}"
  done
  if [[ "${path}" != */* ]]; then
    printf '.\n'
    return 0
  fi

  path="${path%/*}"
  while [[ "${path}" != '/' && "${path}" == */ ]]; do
    path="${path%/}"
  done
  if [[ -z "${path}" ]]; then
    path='/'
  fi
  printf '%s\n' "${path}"
}

### Write the final component of a path with an optional suffix removed.
path::base-name() {
  if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then
    return 64
  fi

  local path="$1"
  local suffix="${2-}"
  local name=''

  if [[ -z "${path}" ]]; then
    printf '\n'
    return 0
  fi
  while [[ "${path}" != '/' && "${path}" == */ ]]; do
    path="${path%/}"
  done
  if [[ "${path}" == '/' ]]; then
    name='/'
  else
    name="${path##*/}"
  fi

  if [[ "$#" -eq 2 && -n "${suffix}" ]] && string::ends-with "${name}" "${suffix}"; then
    name="${name:0:$((${#name} - ${#suffix}))}"
  fi
  printf '%s\n' "${name}"
}

### Test whether a path names a directory.
path::is-directory() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -d "$1" ]]
}

### Test whether a path names an empty directory.
path::is-empty-directory() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  if [[ ! -d "$1" ]]; then
    return 1
  fi

  (
    local entries=()
    shopt -s dotglob nullglob
    entries=("$1"/*)
    [[ "${#entries[@]}" -eq 0 ]]
  )
}

### Test whether the current user may execute a path.
path::is-executable() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -x "$1" ]]
}

### Test whether a path names an executable regular file.
path::is-executable-file() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -f "$1" && -x "$1" ]]
}

### Test whether a path names a regular file.
path::is-regular-file() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -f "$1" ]]
}

### Test whether a path names a symbolic link.
path::is-symbolic-link() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -L "$1" ]]
}

### Test whether the current user may read a path.
path::is-readable() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -r "$1" ]]
}

### Test whether the current user may write a path.
path::is-writable() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  [[ -w "$1" ]]
}

### Write the extension of the final path component.
path::extension() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local name=''
  name="$(path::base-name "$1")" || return "$?"

  case "${name}" in
    '' | '/' | '.' | '..')
      printf '\n'
      ;;
    .*)
      if [[ "${name:1}" != *.* ]]; then
        printf '\n'
      else
        printf '.%s\n' "${name##*.}"
      fi
      ;;
    *.*)
      printf '.%s\n' "${name##*.}"
      ;;
    *)
      printf '\n'
      ;;
  esac
}

### Normalize a path lexically without accessing the file system.
path::normalize() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local path="$1"
  local remaining="$1"
  local absolute='0'
  local part=''
  local parts=()
  local index=''
  local result=''

  if [[ "${path}" == /* ]]; then
    absolute='1'
  fi

  while :; do
    if [[ "${remaining}" == */* ]]; then
      part="${remaining%%/*}"
      remaining="${remaining#*/}"
    else
      part="${remaining}"
      remaining=''
    fi

    case "${part}" in
      '' | '.')
        ;;
      '..')
        if [[ "${#parts[@]}" -gt 0 && "${parts[${#parts[@]}-1]}" != '..' ]]; then
          unset 'parts[${#parts[@]}-1]'
        elif [[ "${absolute}" -eq 0 ]]; then
          parts[${#parts[@]}]='..'
        fi
        ;;
      *)
        parts[${#parts[@]}]="${part}"
        ;;
    esac

    if [[ -z "${remaining}" ]]; then
      break
    fi
  done

  if [[ "${absolute}" -eq 1 ]]; then
    result='/'
  fi
  for ((index = 0; index < ${#parts[@]}; index++)); do
    if [[ -n "${result}" && "${result}" != '/' ]]; then
      result+='/'
    fi
    result+="${parts[index]}"
  done

  if [[ -z "${result}" ]]; then
    result='.'
  fi
  printf '%s\n' "${result}"
}

### Write the lexical relative path from one path to another.
path::relative() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local from=''
  local to=''
  local from_absolute='0'
  local to_absolute='0'
  local remaining=''
  local part=''
  local from_parts=()
  local to_parts=()
  local common='0'
  local index=''
  local result=''

  from="$(path::normalize "$1")" || return "$?"
  to="$(path::normalize "$2")" || return "$?"
  [[ "${from}" == /* ]] && from_absolute='1'
  [[ "${to}" == /* ]] && to_absolute='1'
  if [[ "${from_absolute}" -ne "${to_absolute}" ]]; then
    return 64
  fi

  remaining="${from#/}"
  if [[ "${remaining}" != '.' ]]; then
    while :; do
      if [[ "${remaining}" == */* ]]; then
        part="${remaining%%/*}"
        remaining="${remaining#*/}"
      else
        part="${remaining}"
        remaining=''
      fi
      from_parts[${#from_parts[@]}]="${part}"
      [[ -z "${remaining}" ]] && break
    done
  fi

  remaining="${to#/}"
  if [[ "${remaining}" != '.' ]]; then
    while :; do
      if [[ "${remaining}" == */* ]]; then
        part="${remaining%%/*}"
        remaining="${remaining#*/}"
      else
        part="${remaining}"
        remaining=''
      fi
      to_parts[${#to_parts[@]}]="${part}"
      [[ -z "${remaining}" ]] && break
    done
  fi

  while ((common < ${#from_parts[@]} && common < ${#to_parts[@]})); do
    if [[ "${from_parts[common]}" != "${to_parts[common]}" ]]; then
      break
    fi
    common=$((common + 1))
  done

  for ((index = common; index < ${#from_parts[@]}; index++)); do
    if [[ -n "${result}" ]]; then
      result+='/'
    fi
    result+='..'
  done
  for ((index = common; index < ${#to_parts[@]}; index++)); do
    if [[ -n "${result}" ]]; then
      result+='/'
    fi
    result+="${to_parts[index]}"
  done

  if [[ -z "${result}" ]]; then
    result='.'
  fi
  printf '%s\n' "${result}"
}

### Write the absolute configuration-home directory.
path::config-home() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  if [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
    if [[ "${XDG_CONFIG_HOME}" != /* ]] ||
      ! string::_require-one-line "${XDG_CONFIG_HOME}"; then
      return 64
    fi
    printf '%s\n' "${XDG_CONFIG_HOME}"
    return 0
  fi

  if [[ -z "${HOME:-}" || "${HOME}" != /* ]] ||
    ! string::_require-one-line "${HOME:-}"; then
    return 64
  fi
  printf '%s/.config\n' "${HOME%/}"
}

### Change directory ownership recursively through the root helper.
path::change-owner-recursively-as-root() {
  if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
    return 64
  fi
  if [[ ! -d "$1" || -L "$1" ]]; then
    return 66
  fi
  if ! string::_require-non-empty-line "$2"; then
    return 64
  fi
  if [[ "$#" -eq 3 ]] && ! string::_require-non-empty-line "$3"; then
    return 64
  fi

  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    change-owner-recursively "$@"
}

# shellcheck disable=SC2119,SC2120

### Read one line from standard input and preserve a final partial line.
prompt::_read-line() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  local value=''
  if IFS= read -r value; then
    printf '%s\n' "${value}"
    return 0
  fi
  if [[ -n "${value}" ]]; then
    printf '%s\n' "${value}"
    return 0
  fi
  return 66
}

### Read and normalize a yes-or-no answer.
prompt::confirm() {
  if [[ "$#" -lt 1 || "$#" -gt 2 ]] ||
    ! string::_require-one-line "$1"; then
    return 64
  fi

  local message="$1"
  local default="${2-}"
  local value=''

  if [[ -n "${default}" && "${default}" != 'yes' && "${default}" != 'no' ]]; then
    return 64
  fi

  printf '%s [yes/no]: ' "${message}" >&2
  value="$(prompt::_read-line)" || return "$?"
  value="$(string::lower "${value}")" || return "$?"
  case "${value}" in
    y | yes)
      printf 'yes\n'
      ;;
    n | no)
      printf 'no\n'
      ;;
    '')
      if [[ -z "${default}" ]]; then
        return 64
      fi
      printf '%s\n' "${default}"
      ;;
    *)
      return 64
      ;;
  esac
}

### Read one line and substitute a default only for empty input.
prompt::read-line-with-default() {
  if [[ "$#" -ne 2 ]] || ! string::_require-one-line "$1"; then
    return 64
  fi

  local value=''
  printf '%s: ' "$1" >&2
  value="$(prompt::_read-line)" || return "$?"
  if [[ -z "${value}" ]]; then
    value="$2"
  fi
  printf '%s\n' "${value}"
}

### Read and normalize a yes, no, or cancel answer.
prompt::confirm-or-cancel() {
  if [[ "$#" -lt 1 || "$#" -gt 2 ]] ||
    ! string::_require-one-line "$1"; then
    return 64
  fi

  local message="$1"
  local default="${2-}"
  local value=''

  case "${default}" in
    '' | yes | no | cancel)
      ;;
    *)
      return 64
      ;;
  esac

  printf '%s [yes/no/cancel]: ' "${message}" >&2
  value="$(prompt::_read-line)" || return "$?"
  value="$(string::lower "${value}")" || return "$?"
  case "${value}" in
    y | yes)
      printf 'yes\n'
      ;;
    n | no)
      printf 'no\n'
      ;;
    c | cancel)
      printf 'cancel\n'
      ;;
    '')
      if [[ -z "${default}" ]]; then
        return 64
      fi
      printf '%s\n' "${default}"
      ;;
    *)
      return 64
      ;;
  esac
}

### Display indexed choices and write the selected value.
prompt::select-one() {
  if [[ "$#" -lt 2 ]] || ! string::_require-one-line "$1"; then
    return 64
  fi

  local message="$1"
  local items=()
  local item=''
  local index=''
  local selected=''
  shift
  items=("$@")

  for item in "${items[@]}"; do
    if ! string::_require-one-line "${item}"; then
      return 64
    fi
  done

  printf '%s\n' "${message}" >&2
  for ((index = 0; index < ${#items[@]}; index++)); do
    printf '%s) %s\n' "$((index + 1))" "${items[index]}" >&2
  done
  printf 'Selection: ' >&2

  selected="$(prompt::_read-line)" || return "$?"
  if ! number::_is-positive-integer-at-most "${selected}" 2147483647; then
    return 64
  fi
  if ((10#${selected} > ${#items[@]})); then
    return 64
  fi
  printf '%s\n' "${items[10#${selected}-1]}"
}

# shellcheck disable=SC2119,SC2120

### Write milliseconds from the requested monotonic clock.
time::_clock-milliseconds() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  command -v perl >/dev/null 2>&1 || return 69

  local operating_system=''
  operating_system="$(system::operating-system)" || return 69
  case "${operating_system}:$1" in
    linux:monotonic)
      perl -MTime::HiRes=clock_gettime,CLOCK_MONOTONIC \
        -e 'printf "%d\n", int(clock_gettime(CLOCK_MONOTONIC) * 1000)' \
        2>/dev/null || return 69
      ;;
    linux:boottime)
      perl -e '
        use strict;
        use warnings;

        open my $input, "<", "/proc/uptime" or exit 69;
        my $line = <$input>;
        close $input or exit 69;
        exit 69 unless defined($line)
          && $line =~ /\A([0-9]+)(?:\.([0-9]+))?[[:space:]]/;

        my $seconds = $1;
        my $fraction = defined($2) ? $2 : "";
        $fraction .= "000";
        printf "%d\n", ($seconds * 1000) + substr($fraction, 0, 3);
      ' 2>/dev/null || return 69
      ;;
    darwin:monotonic)
      perl -MTime::HiRes=clock_gettime,CLOCK_UPTIME_RAW \
        -e 'printf "%d\n", int(clock_gettime(CLOCK_UPTIME_RAW) * 1000)' \
        2>/dev/null || return 69
      ;;
    darwin:boottime)
      perl -MTime::HiRes=clock_gettime,CLOCK_MONOTONIC_RAW \
        -e 'printf "%d\n", int(clock_gettime(CLOCK_MONOTONIC_RAW) * 1000)' \
        2>/dev/null || return 69
      ;;
    *)
      return 69
      ;;
  esac
}

### Write Unix-epoch milliseconds from the real-time clock.
time::_realtime-milliseconds() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  command -v perl >/dev/null 2>&1 || return 69
  perl -MTime::HiRes=time -e 'printf "%d\n", int(time() * 1000)' 2>/dev/null ||
    return 69
}

### Format an epoch-millisecond value in a fixed date-time form.
time::_format-milliseconds() {
  if [[ "$#" -ne 2 ]] || ! number::_is-non-negative-integer "$1"; then
    return 64
  fi
  command -v perl >/dev/null 2>&1 || return 69

  perl -MPOSIX=strftime -e '
    use strict;
    use warnings;
    my ($milliseconds, $mode) = @ARGV;
    exit 64 unless defined $milliseconds && $milliseconds =~ /\A[0-9]+\z/;
    my $seconds = int($milliseconds / 1000);
    my $fraction = $milliseconds % 1000;
    my ($base, $offset);
    if ($mode eq "utc-ms") {
      $base = strftime("%Y-%m-%dT%H:%M:%S", gmtime($seconds));
      printf "%s.%03dZ\n", $base, $fraction;
    } elsif ($mode eq "utc-s") {
      print strftime("%Y-%m-%dT%H:%M:%SZ", gmtime($seconds)), "\n";
    } elsif ($mode eq "utc-date") {
      print strftime("%Y-%m-%d", gmtime($seconds)), "\n";
    } elsif ($mode eq "local-ms" || $mode eq "local-s") {
      my @local = localtime($seconds);
      $base = strftime("%Y-%m-%dT%H:%M:%S", @local);
      $offset = strftime("%z", @local);
      $offset =~ s/([+-][0-9]{2})([0-9]{2})\z/$1:$2/;
      exit 69 unless $offset =~ /\A[+-][0-9]{2}:[0-9]{2}\z/;
      if ($mode eq "local-ms") {
        printf "%s.%03d%s\n", $base, $fraction, $offset;
      } else {
        print $base, $offset, "\n";
      }
    } elsif ($mode eq "local-date") {
      print strftime("%Y-%m-%d", localtime($seconds)), "\n";
    } else {
      exit 64;
    }
  ' -- "$1" "$2" 2>/dev/null || {
    local status="$?"
    [[ "${status}" -eq 64 ]] && return 64
    return 69
  }
}

### Report that the portable time provider is unavailable.
time::_provider-error() {
  console::_write-error 'The portable time provider is unavailable.'
  return 69
}

### Write monotonic milliseconds that exclude suspended time.
time::monotonic-milliseconds() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  time::_clock-milliseconds monotonic || time::_provider-error
}

### Write milliseconds since boot including suspended time.
time::boottime-milliseconds() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  time::_clock-milliseconds boottime || time::_provider-error
}

### Write Unix-epoch milliseconds.
time::unix-milliseconds() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  time::_realtime-milliseconds || time::_provider-error
}

### Write Unix-epoch seconds rounded down.
time::unix-seconds() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  local milliseconds=''
  milliseconds="$(time::_realtime-milliseconds)" || {
    time::_provider-error
    return 69
  }
  printf '%s\n' "$((milliseconds / 1000))"
}

### Write Unix-epoch days rounded down.
time::unix-days() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  local milliseconds=''
  milliseconds="$(time::_realtime-milliseconds)" || {
    time::_provider-error
    return 69
  }
  printf '%s\n' "$((milliseconds / 86400000))"
}

### Format the current real-time clock in a requested date-time form.
time::_date-time() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  local milliseconds=''
  milliseconds="$(time::_realtime-milliseconds)" || {
    time::_provider-error
    return 69
  }
  time::_format-milliseconds "${milliseconds}" "$1" || {
    local status="$?"
    [[ "${status}" -eq 64 ]] && return 64
    time::_provider-error
    return 69
  }
}

### Write the current UTC date and time with milliseconds.
time::utc-date-time-milliseconds() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time utc-ms
}

### Write the current UTC date and time with seconds.
time::utc-date-time-seconds() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time utc-s
}

### Write the current UTC date.
time::utc-date() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time utc-date
}

### Write the current local date and time with milliseconds and an offset.
time::local-date-time-milliseconds() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time local-ms
}

### Write the current local date and time with seconds and an offset.
time::local-date-time-seconds() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time local-s
}

### Write the current local date.
time::local-date() {
  [[ "$#" -eq 0 ]] || return 64
  time::_date-time local-date
}


### Write every message line with a timestamp, level, and command name.
log::_write() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  local level="$1"
  local remaining="$2"
  local line=''
  local timestamp=''

  while [[ "${remaining}" == *$'\n'* ]]; do
    line="${remaining%%$'\n'*}"
    timestamp="$(time::local-date-time-milliseconds)" || return "$?"
    printf '%s [%s] [%s] %s\n' \
      "${timestamp}" "${level}" "${BASHSTOCK_NAME:-bashstock}" "${line}" >&2
    remaining="${remaining#*$'\n'}"
  done

  timestamp="$(time::local-date-time-milliseconds)" || return "$?"
  printf '%s [%s] [%s] %s\n' \
    "${timestamp}" "${level}" "${BASHSTOCK_NAME:-bashstock}" "${remaining}" >&2
}

### Write an informational log message.
log::info() {
  [[ "$#" -eq 1 ]] || return 64
  log::_write INFO "$1"
}

### Write a warning log message.
log::warn() {
  [[ "$#" -eq 1 ]] || return 64
  log::_write WARN "$1"
}

### Write an error log message without exiting.
log::error() {
  [[ "$#" -eq 1 ]] || return 64
  log::_write ERROR "$1"
}


### Require a named JSON-derived value to be neither empty nor null.
json::require-present() {
  if [[ "$#" -ne 2 ]] || ! string::_require-non-empty-line "$1"; then
    return 64
  fi

  if [[ -n "$2" && "$2" != 'null' ]]; then
    return 0
  fi

  console::_write-error "$1 must be present."
  return 64
}


### Require exactly one named option value to be non-empty.
option::require-single() {
  if [[ "$#" -lt 4 ]] || (($# % 2 != 0)); then
    return 64
  fi

  local count='0'
  local names=''
  local name=''
  local value=''

  while [[ "$#" -gt 0 ]]; do
    name="$1"
    value="$2"
    shift 2

    if ! string::_require-non-empty-line "${name}"; then
      return 64
    fi
    if [[ -n "${names}" ]]; then
      names+=', '
    fi
    names+="${name}"
    if [[ -n "${value}" ]]; then
      count=$((count + 1))
    fi
  done

  if [[ "${count}" -eq 1 ]]; then
    return 0
  fi
  console::_write-error "Exactly one option must be set: ${names}"
  return 64
}

# shellcheck disable=SC2234

### Require a readable regular file that is not a symbolic link.
file::_require-existing() {
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    return 64
  fi
  if [[ -L "$1" || ! -f "$1" || ! -r "$1" ]]; then
    return 66
  fi
}

### Require a one-line expression that compiles as a Perl regular expression.
file::_require-expression() {
  if [[ "$#" -ne 1 ]] || ! string::_require-one-line "$1"; then
    return 64
  fi
  command -v perl >/dev/null 2>&1 || return 69
  perl -e 'my $expression = shift; eval { qr/$expression/ }; exit($@ ? 64 : 0)' \
    -- "$1" 2>/dev/null
}

### Copy file content and metadata to another path.
file::_copy-metadata-and-content() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi

  case "$(system::operating-system)" in
    darwin)
      cp -p "$1" "$2" >/dev/null 2>&1
      ;;
    linux)
      cp --preserve=all "$1" "$2" >/dev/null 2>&1
      ;;
    *)
      return 69
      ;;
  esac
}

### Create a temporary path beside the target file.
file::_temporary-path() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi

  local directory=''
  local name=''
  directory="$(path::directory-name "$1")" || return "$?"
  name="$(path::base-name "$1")" || return "$?"
  command -v mktemp >/dev/null 2>&1 || return 69
  mktemp "${directory}/.${name}.bashstock.XXXXXX" 2>/dev/null || return 74
}

### Prepare a metadata-preserving replacement file.
file::_prepare-replacement() {
  if [[ "$#" -ne 4 ]]; then
    return 64
  fi

  local source="$1"
  local expression="$2"
  local replacement="$3"
  local append_when_missing="$4"
  local temporary=''
  local status=''

  temporary="$(file::_temporary-path "${source}")" || return "$?"
  if ! file::_copy-metadata-and-content "${source}" "${temporary}"; then
    rm -f -- "${temporary}"
    return 74
  fi

  if perl -e '
    use strict;
    use warnings;
    my ($source, $target, $expression, $replacement, $append_when_missing) = @ARGV;
    my $regex = eval { qr/$expression/ };
    exit 64 if $@;
    open my $input, "<", $source or exit 74;
    open my $output, ">", $target or exit 74;
    binmode $input;
    binmode $output;
    my $changed = 0;
    my $saw_bytes = 0;
    my $last_byte = "";
    while (defined(my $line = <$input>)) {
      $saw_bytes = 1 if length $line;
      my $count = ($line =~ s/$regex/$replacement/);
      $changed = 1 if $count;
      $last_byte = substr($line, -1, 1) if length $line;
      print {$output} $line or exit 74;
    }
    close $input or exit 74;
    if (!$changed && $append_when_missing) {
      print {$output} "\n" if $saw_bytes && $last_byte ne "\n";
      print {$output} $replacement, "\n" or exit 74;
      $changed = 1;
    }
    close $output or exit 74;
    exit($changed ? 0 : 1);
  ' -- "${source}" "${temporary}" "${expression}" "${replacement}" \
    "${append_when_missing}"; then
    printf '%s\n' "${temporary}"
    return 0
  else
    status="$?"
  fi

  rm -f -- "${temporary}"
  case "${status}" in
    1 | 64 | 69 | 74)
      return "${status}"
      ;;
    *)
      return 74
      ;;
  esac
}

### Test whether any file line matches a Perl regular expression.
file::contains-match() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  file::_require-existing "$1" || return "$?"
  file::_require-expression "$2" || return "$?"

  perl -e '
    use strict;
    use warnings;
    my ($path, $expression) = @ARGV;
    my $regex = eval { qr/$expression/ };
    exit 64 if $@;
    open my $input, "<", $path or exit 66;
    while (defined(my $line = <$input>)) {
      exit 0 if $line =~ $regex;
    }
    exit 1;
  ' -- "$1" "$2" 2>/dev/null
}

### Test a file against an expected SHA-256 digest.
file::verify-sha256() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  file::_require-existing "$1" || return "$?"
  if ! ( [[ "$2" =~ ^[0-9A-Fa-f]{64}$ ]] ); then
    return 64
  fi

  local output=''
  local actual=''
  case "$(system::operating-system)" in
    darwin)
      command -v shasum >/dev/null 2>&1 || return 69
      output="$(shasum -a 256 -- "$1" 2>/dev/null)" || return 74
      ;;
    linux)
      command -v sha256sum >/dev/null 2>&1 || return 69
      output="$(sha256sum -- "$1" 2>/dev/null)" || return 74
      ;;
    *)
      return 69
      ;;
  esac
  actual="${output%% *}"
  [[ "$(string::lower "${actual}")" == "$(string::lower "$2")" ]]
}

### Append text without conversion using the current user's permissions.
file::append-text() {
  if [[ "$#" -ne 2 || -z "$1" || -L "$1" ]]; then
    return 64
  fi
  if [[ -e "$1" && ! -f "$1" ]]; then
    return 66
  fi

  printf '%s' "$2" >>"$1" 2>/dev/null || return 74
}

### Append text without conversion through the root helper.
file::append-text-as-root() {
  if [[ "$#" -ne 2 || -z "$1" || -L "$1" ]]; then
    return 64
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    append-text "$1" "$2"
}

### Replace the first Perl regular-expression match on every file line.
file::replace-text() {
  if [[ "$#" -ne 3 ]] ||
    ! string::_require-one-line "$2" ||
    ! string::_require-one-line "$3"; then
    return 64
  fi
  file::_require-existing "$1" || return "$?"
  file::_require-expression "$2" || return "$?"

  local temporary=''
  temporary="$(file::_prepare-replacement "$1" "$2" "$3" 0)" || return "$?"
  if ! mv -f -- "${temporary}" "$1" 2>/dev/null; then
    rm -f -- "${temporary}"
    return 74
  fi
}

### Replace line matches through the root helper.
file::replace-text-as-root() {
  if [[ "$#" -ne 3 ]] ||
    ! string::_require-one-line "$2" ||
    ! string::_require-one-line "$3"; then
    return 64
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    replace-text "$@"
}

### Replace line matches across files with rollback on failure.
file::_replace-text-in-files() {
  if [[ "$#" -lt 3 ]]; then
    return 64
  fi

  local expression="$1"
  local replacement="$2"
  local paths=()
  local prepared=()
  local backups=()
  local path=''
  local temporary=''
  local backup=''
  local status=''
  local index=''
  local restore_status='0'
  shift 2
  paths=("$@")

  if ! string::_require-one-line "${expression}" ||
    ! string::_require-one-line "${replacement}"; then
    return 64
  fi
  file::_require-expression "${expression}" || return "$?"
  for path in "${paths[@]}"; do
    file::_require-existing "${path}" || return "$?"
  done

  for path in "${paths[@]}"; do
    backup="$(file::_temporary-path "${path}")" || {
      status="$?"
      break
    }
    if ! file::_copy-metadata-and-content "${path}" "${backup}"; then
      rm -f -- "${backup}"
      status='74'
      break
    fi
    backups[${#backups[@]}]="${backup}"

    temporary="$(file::_prepare-replacement "${path}" "${expression}" "${replacement}" 0)" || {
      status="$?"
      break
    }
    prepared[${#prepared[@]}]="${temporary}"
  done

  if [[ -n "${status}" ]]; then
    for temporary in "${prepared[@]}" "${backups[@]}"; do
      [[ -n "${temporary}" ]] && rm -f -- "${temporary}"
    done
    return "${status}"
  fi

  for ((index = 0; index < ${#paths[@]}; index++)); do
    if ! mv -f -- "${prepared[index]}" "${paths[index]}" 2>/dev/null; then
      status='74'
      break
    fi
  done

  if [[ -n "${status}" ]]; then
    for ((index = 0; index < ${#backups[@]}; index++)); do
      if ! mv -f -- "${backups[index]}" "${paths[index]}" 2>/dev/null; then
        restore_status='74'
      fi
    done
    for temporary in "${prepared[@]}" "${backups[@]}"; do
      [[ -n "${temporary}" ]] && rm -f -- "${temporary}"
    done
    [[ "${restore_status}" -eq 0 ]] || return 74
    return "${status}"
  fi

  for backup in "${backups[@]}"; do
    rm -f -- "${backup}"
  done
}

### Replace line matches across multiple files.
file::replace-text-in-files() {
  file::_replace-text-in-files "$@"
}

### Replace line matches across multiple files through the root helper.
file::replace-text-in-files-as-root() {
  if [[ "$#" -lt 3 ]]; then
    return 64
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    replace-text-in-files "$@"
}

### Replace line matches or append one line when no match exists.
file::replace-or-append-text() {
  if [[ "$#" -ne 3 ]] ||
    ! string::_require-one-line "$2" ||
    ! string::_require-one-line "$3"; then
    return 64
  fi
  file::_require-existing "$1" || return "$?"
  file::_require-expression "$2" || return "$?"

  local temporary=''
  temporary="$(file::_prepare-replacement "$1" "$2" "$3" 1)" || return "$?"
  if ! mv -f -- "${temporary}" "$1" 2>/dev/null; then
    rm -f -- "${temporary}"
    return 74
  fi
}

### Replace line matches or append through the root helper.
file::replace-or-append-text-as-root() {
  if [[ "$#" -ne 3 ]] ||
    ! string::_require-one-line "$2" ||
    ! string::_require-one-line "$3"; then
    return 64
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    replace-or-append-text "$@"
}


### Write the identifier of the supported operating-system provider.
platform::_identifier() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi

  local operating_system=''
  local key=''
  local value=''
  operating_system="$(system::operating-system)" || return "$?"
  if [[ "${operating_system}" == 'darwin' ]]; then
    printf 'darwin\n'
    return 0
  fi
  if [[ "${operating_system}" != 'linux' || ! -r /etc/os-release ]]; then
    printf 'unknown\n'
    return 0
  fi

  while IFS='=' read -r key value; do
    if [[ "${key}" == 'ID' ]]; then
      value="${value#\"}"
      value="${value%\"}"
      case "${value}" in
        ubuntu | fedora)
          printf '%s\n' "${value}"
          ;;
        *)
          printf 'unknown\n'
          ;;
      esac
      return 0
    fi
  done </etc/os-release

  printf 'unknown\n'
}

### Return unavailable until an operating-system provider defines user creation.
platform::_create-system-user() {
  return 69
}

### Return unavailable until an operating-system provider defines login creation.
platform::_create-login-user() {
  return 69
}

### Return unavailable until an operating-system provider defines ownership changes.
platform::_change-owner-recursively() {
  return 69
}

case "$(platform::_identifier)" in
  darwin)
# shellcheck disable=SC2234

### Create a non-login macOS role account.
platform::_create-system-user() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  command -v sysadminctl >/dev/null 2>&1 || return 69
  command -v dscl >/dev/null 2>&1 || return 69

  local used=''
  local uid=''
  used="$(dscl . -list /Users UniqueID 2>/dev/null)" || return 74
  for ((uid = 450; uid <= 499; uid++)); do
    if ! ( [[ "${used}" =~ [[:space:]]${uid}([[:space:]]|$) ]] ); then
      sysadminctl -addUser "$1" -UID "${uid}" -home /var/empty \
        -shell /usr/bin/false -roleAccount >/dev/null || return 73
      return 0
    fi
  done
  return 73
}

### Create a macOS login account and roll it back after password failure.
platform::_create-login-user() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  command -v sysadminctl >/dev/null 2>&1 || return 69

  if sysadminctl -addUser "$1" -fullName "$2" -home "/Users/$1" \
    -shell /bin/bash -password - </dev/tty >/dev/tty 2>/dev/tty; then
    return 0
  fi

  if id -u "$1" >/dev/null 2>&1; then
    if ! sysadminctl -deleteUser "$1" -secure </dev/tty >/dev/tty 2>/dev/tty; then
      console::_write-error \
        "Failed to restore the account after password setup: $1, /Users/$1"
      return 74
    fi
  fi
  return 73
}

### Change ownership recursively without crossing macOS mount points.
platform::_change-owner-recursively() {
  if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
    return 64
  fi
  command -v find >/dev/null 2>&1 || return 69
  command -v chown >/dev/null 2>&1 || return 69

  local group="${3-}"
  if [[ -z "${group}" ]]; then
    group="$(id -gn "$2" 2>/dev/null)" || return 66
  fi
  find -x "$1" -exec chown -h "${2}:${group}" {} + || return 74
}

    ;;
  ubuntu)

### Create a non-login Ubuntu system account.
platform::_create-system-user() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  command -v useradd >/dev/null 2>&1 || return 69
  useradd --system --no-create-home --home-dir /nonexistent \
    --shell /usr/sbin/nologin "$1" || return 73
}

### Create an Ubuntu login account and roll it back after password failure.
platform::_create-login-user() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  command -v useradd >/dev/null 2>&1 || return 69
  command -v passwd >/dev/null 2>&1 || return 69

  useradd --create-home --home-dir "/home/$1" --shell /bin/bash \
    --comment "$2" "$1" || return 73
  if passwd "$1" </dev/tty >/dev/tty 2>/dev/tty; then
    return 0
  fi

  if ! userdel --remove "$1" >/dev/null 2>&1; then
    console::_write-error \
      "Failed to restore the account after password setup: $1, /home/$1"
    return 74
  fi
  return 73
}

### Change ownership recursively without crossing Ubuntu mount points.
platform::_change-owner-recursively() {
  if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
    return 64
  fi
  command -v find >/dev/null 2>&1 || return 69
  command -v chown >/dev/null 2>&1 || return 69

  local group="${3-}"
  if [[ -z "${group}" ]]; then
    group="$(id -gn "$2" 2>/dev/null)" || return 66
  fi
  find "$1" -xdev -exec chown --no-dereference "${2}:${group}" {} + || return 74
}

    ;;
  fedora)

### Create a non-login Fedora system account.
platform::_create-system-user() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  command -v useradd >/dev/null 2>&1 || return 69
  useradd --system --no-create-home --home-dir /nonexistent \
    --shell /usr/sbin/nologin "$1" || return 73
}

### Create a Fedora login account and roll it back after password failure.
platform::_create-login-user() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  command -v useradd >/dev/null 2>&1 || return 69
  command -v passwd >/dev/null 2>&1 || return 69

  useradd --create-home --home-dir "/home/$1" --shell /bin/bash \
    --comment "$2" "$1" || return 73
  if passwd "$1" </dev/tty >/dev/tty 2>/dev/tty; then
    return 0
  fi

  if ! userdel --remove "$1" >/dev/null 2>&1; then
    console::_write-error \
      "Failed to restore the account after password setup: $1, /home/$1"
    return 74
  fi
  return 73
}

### Change ownership recursively without crossing Fedora mount points.
platform::_change-owner-recursively() {
  if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
    return 64
  fi
  command -v find >/dev/null 2>&1 || return 69
  command -v chown >/dev/null 2>&1 || return 69

  local group="${3-}"
  if [[ -z "${group}" ]]; then
    group="$(id -gn "$2" 2>/dev/null)" || return 66
  fi
  find "$1" -xdev -exec chown --no-dereference "${2}:${group}" {} + || return 74
}

    ;;
esac

# shellcheck disable=SC2234

### Write the effective user's name.
user::name() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  id -un 2>/dev/null || return 74
}

### Write the effective user's primary group name.
user::primary-group() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  id -gn 2>/dev/null || return 74
}

### Test whether the effective user is root.
user::is-root() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  [[ "${EUID}" -eq 0 ]]
}

### Test whether a local user account exists.
user::exists() {
  if [[ "$#" -ne 1 || -z "$1" || "$1" == -* ]] ||
    ! string::_require-one-line "$1"; then
    return 64
  fi
  id -u "$1" >/dev/null 2>&1
}

### Create a non-login system account through the root helper.
user::create-system-as-root() {
  if [[ "$#" -ne 1 ]] || ! ( [[ "$1" =~ ^_[a-z][a-z0-9_-]*$ ]] ); then
    return 64
  fi
  if user::exists "$1"; then
    return 73
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    create-system-user "$1"
}

### Create a local login account through the root helper.
user::create-login-as-root() {
  if [[ "$#" -ne 2 ]] ||
    ! ( [[ "$1" =~ ^[a-z][a-z0-9_-]*$ ]] ) ||
    [[ -z "$2" || "$2" == *:* || "$2" == *[[:cntrl:]]* ]]; then
    return 64
  fi
  if user::exists "$1"; then
    return 73
  fi
  if ! terminal::is-available; then
    console::_write-error 'A controlling terminal is required to set the password.'
    return 66
  fi
  command::run-as-root "${BASHSTOCK_ROOT}/libexec/bashstock-root" \
    create-login-user "$1" "$2"
}

# shellcheck disable=SC2119,SC2120

### Require one non-empty, single-line AWS argument.
aws::_require-value() {
  if [[ "$#" -ne 1 || -z "$1" ]] || ! string::_require-one-line "$1"; then
    return 64
  fi
}

### Run the AWS CLI and normalize authentication and service failures.
aws::_cli() {
  if [[ "$#" -lt 1 ]]; then
    return 64
  fi
  command -v aws >/dev/null 2>&1 || return 69
  command -v mktemp >/dev/null 2>&1 || return 69

  local output=''
  local error=''
  local status=''
  output="$(mktemp "${TMPDIR:-/tmp}/bashstock-aws-output.XXXXXX")" || return 74
  error="$(mktemp "${TMPDIR:-/tmp}/bashstock-aws-error.XXXXXX")" || {
    rm -f -- "${output}"
    return 74
  }

  if command aws "$@" >"${output}" 2>"${error}"; then
    cat "${output}"
    rm -f -- "${output}" "${error}"
    return 0
  else
    status="$?"
  fi

  if grep -Eiq \
    'AccessDenied|Unauthorized|ExpiredToken|InvalidClientTokenId|Unable to locate credentials|NoCredentialProviders' \
    "${error}"; then
    status='77'
  else
    status='75'
  fi
  rm -f -- "${output}" "${error}"
  return "${status}"
}

### Request one IMDSv2 session token.
aws::_imds-token() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  command -v curl >/dev/null 2>&1 || return 69

  local token=''
  token="$(
    curl --silent --show-error --fail --noproxy '*' \
      --connect-timeout 1 --max-time 2 \
      --request PUT \
      --header 'X-aws-ec2-metadata-token-ttl-seconds: 60' \
      'http://169.254.169.254/latest/api/token' 2>/dev/null
  )" || return 75
  if [[ -z "${token}" || "${token}" == *[[:cntrl:]]* ]]; then
    return 75
  fi
  printf '%s\n' "${token}"
}

### Read one metadata path with an IMDSv2 token.
aws::_imds-get() {
  if [[ "$#" -ne 2 ]]; then
    return 64
  fi
  command -v curl >/dev/null 2>&1 || return 69
  command -v mktemp >/dev/null 2>&1 || return 69

  local path="$1"
  local token="$2"
  local output=''
  local status=''
  local http_status=''
  output="$(mktemp "${TMPDIR:-/tmp}/bashstock-imds.XXXXXX")" || return 74
  if [[ -z "${token}" || "${token}" == *[[:cntrl:]]* ]]; then
    rm -f -- "${output}"
    return 75
  fi

  if http_status="$(
    curl --silent --show-error --noproxy '*' \
      --connect-timeout 1 --max-time 2 \
      --output "${output}" --write-out '%{http_code}' \
      --header "X-aws-ec2-metadata-token: ${token}" \
      "http://169.254.169.254/latest/meta-data/${path}" 2>/dev/null
  )"; then
    :
  else
    status="$?"
    rm -f -- "${output}"
    [[ "${status}" -eq 127 ]] && return 69
    return 75
  fi

  case "${http_status}" in
    200)
      cat "${output}"
      status='0'
      ;;
    404)
      status='1'
      ;;
    *)
      status='75'
      ;;
  esac
  rm -f -- "${output}"
  return "${status}"
}

### Read the EC2 instance identity document with an IMDSv2 token.
aws::_imds-document() {
  if [[ "$#" -ne 1 ]]; then
    return 64
  fi
  command -v curl >/dev/null 2>&1 || return 69
  if [[ -z "$1" || "$1" == *[[:cntrl:]]* ]]; then
    return 75
  fi

  curl --silent --show-error --fail --noproxy '*' \
    --connect-timeout 1 --max-time 2 \
    --header "X-aws-ec2-metadata-token: $1" \
    'http://169.254.169.254/latest/dynamic/instance-identity/document' 2>/dev/null ||
    return 75
}

### Test whether IMDSv2 is available for the current instance.
aws::is-ec2-instance() {
  if [[ "$#" -ne 0 ]]; then
    return 64
  fi
  aws::_imds-token >/dev/null 2>&1 || return 1
}

### Write one validated EC2 instance metadata value.
aws::instance-metadata() {
  if [[ "$#" -ne 1 || -z "$1" || "$1" == /* || "$1" == */ ||
    "$1" == *'//'* || "$1" == *'?'* || "$1" == *'#'* ||
    "$1" == *[[:cntrl:]]* ]]; then
    return 64
  fi

  local remaining="$1"
  local part=''
  local token=''
  while :; do
    if [[ "${remaining}" == */* ]]; then
      part="${remaining%%/*}"
      remaining="${remaining#*/}"
    else
      part="${remaining}"
      remaining=''
    fi
    if [[ "${part}" == '.' || "${part}" == '..' || -z "${part}" ]]; then
      return 64
    fi
    [[ -z "${remaining}" ]] && break
  done

  token="$(aws::_imds-token)" || return "$?"
  aws::_imds-get "$1" "${token}"
}

### Write the current EC2 instance identifier.
aws::instance-id() {
  [[ "$#" -eq 0 ]] || return 64
  aws::instance-metadata instance-id
}

### Write the current EC2 instance region.
aws::instance-region() {
  [[ "$#" -eq 0 ]] || return 64

  local token=''
  local document=''
  token="$(aws::_imds-token)" || return "$?"
  document="$(aws::_imds-document "${token}")" || return "$?"
  command -v perl >/dev/null 2>&1 || return 69
  printf '%s' "${document}" |
    perl -MJSON::PP -0777 -e '
      my $data = eval { decode_json(<STDIN>) };
      exit 75 if $@ || ref($data) ne "HASH";
      my $value = $data->{region};
      exit 75 unless defined $value && !ref($value) && length($value);
      print $value, "\n";
    ' 2>/dev/null
}

### Write the current EC2 instance availability zone.
aws::instance-availability-zone() {
  [[ "$#" -eq 0 ]] || return 64
  aws::instance-metadata placement/availability-zone
}

### Write the current EC2 instance private IPv4 address.
aws::instance-private-ip() {
  [[ "$#" -eq 0 ]] || return 64
  aws::instance-metadata local-ipv4
}

### Write all tags for one EC2 instance.
aws::instance-tags() {
  if [[ "$#" -ne 2 ]] || ! aws::_require-value "$1" || ! aws::_require-value "$2"; then
    return 64
  fi
  aws::_cli ec2 describe-tags \
    --filters "Name=resource-id,Values=$1" \
    --region "$2" --output json
}

### Write one EC2 instance tag value.
aws::instance-tag() {
  if [[ "$#" -ne 3 ]] ||
    ! aws::_require-value "$1" ||
    ! aws::_require-value "$2" ||
    ! aws::_require-value "$3"; then
    return 64
  fi

  local tags=''
  command -v perl >/dev/null 2>&1 || return 69
  tags="$(aws::instance-tags "$1" "$2")" || return "$?"
  printf '%s' "${tags}" |
    perl -MJSON::PP -0777 -e '
      my $key = shift;
      my $data = eval { decode_json(<STDIN>) };
      exit 75 if $@ || ref($data) ne "HASH" || ref($data->{Tags}) ne "ARRAY";
      for my $tag (@{$data->{Tags}}) {
        next unless ref($tag) eq "HASH";
        if (defined($tag->{Key}) && $tag->{Key} eq $key) {
          exit 75 if !defined($tag->{Value}) || ref($tag->{Value});
          print $tag->{Value}, "\n";
          exit 0;
        }
      }
      exit 1;
    ' -- "$3" 2>/dev/null
}

### Wait for one EC2 instance tag to become available.
aws::wait-for-instance-tag() {
  if [[ "$#" -ne 5 ]] ||
    ! aws::_require-value "$1" ||
    ! aws::_require-value "$2" ||
    ! aws::_require-value "$3" ||
    ! number::_is-positive-integer-at-most "$4" 2147483647 ||
    ! number::_is-positive-integer-at-most "$5" 2147483647; then
    return 64
  fi

  local instance_id="$1"
  local region="$2"
  local key="$3"
  local timeout_milliseconds="$(($4 * 1000))"
  local interval_seconds="$5"
  local start=''
  local current=''
  local value=''
  local status=''

  start="$(time::boottime-milliseconds)" || return "$?"
  number::_is-non-negative-integer-at-most "${start}" 9223372036854775807 ||
    return 69
  while :; do
    if value="$(aws::instance-tag "${instance_id}" "${region}" "${key}")"; then
      printf '%s\n' "${value}"
      return 0
    else
      status="$?"
    fi
    if [[ "${status}" -ne 1 ]]; then
      return "${status}"
    fi

    current="$(time::boottime-milliseconds)" || return "$?"
    number::_is-non-negative-integer-at-most "${current}" 9223372036854775807 ||
      return 69
    if ((current - start >= timeout_milliseconds)); then
      return 75
    fi
    sleep "${interval_seconds}" || return 75
  done
}

### Write EC2 instances that have a requested tag.
aws::instances-with-tag() {
  if [[ "$#" -ne 3 ]] ||
    ! aws::_require-value "$1" ||
    ! aws::_require-value "$2" ||
    ! aws::_require-value "$3"; then
    return 64
  fi

  aws::_cli ec2 describe-instances \
    --filters "Name=tag:$1,Values=$2" \
    'Name=instance-state-name,Values=pending,running' \
    --region "$3" --output json
}

### Write the Auto Scaling group that contains an EC2 instance.
aws::auto-scaling-group() {
  if [[ "$#" -ne 2 ]] || ! aws::_require-value "$1" || ! aws::_require-value "$2"; then
    return 64
  fi

  local result=''
  result="$(
    aws::_cli autoscaling describe-auto-scaling-groups \
      --auto-scaling-group-names "$1" \
      --region "$2" \
      --query 'AutoScalingGroups[0]' \
      --output json
  )" || return "$?"
  if [[ -z "${result}" || "${result}" == 'null' || "${result}" == 'None' ]]; then
    return 1
  fi
  printf '%s\n' "${result}"
}

### Write running or pending instances in an Auto Scaling group.
aws::instances-in-auto-scaling-group() {
  if [[ "$#" -ne 2 ]] || ! aws::_require-value "$1" || ! aws::_require-value "$2"; then
    return 64
  fi

  local group=''
  local instance_ids=''
  local ids=()
  local id=''
  command -v perl >/dev/null 2>&1 || return 69
  group="$(aws::auto-scaling-group "$1" "$2")" || return "$?"
  instance_ids="$(
    printf '%s' "${group}" |
      perl -MJSON::PP -0777 -e '
        my $data = eval { decode_json(<STDIN>) };
        exit 75 if $@ || ref($data) ne "HASH";
        my $instances = $data->{Instances};
        exit 75 unless ref($instances) eq "ARRAY";
        for my $instance (@$instances) {
          next unless ref($instance) eq "HASH";
          my $id = $instance->{InstanceId};
          exit 75 unless defined($id) && !ref($id) && $id !~ /\n/;
          print $id, "\n";
        }
      ' 2>/dev/null
  )" || return "$?"

  if [[ -z "${instance_ids}" ]]; then
    printf '{"Reservations":[]}\n'
    return 0
  fi
  while IFS= read -r id; do
    ids[${#ids[@]}]="${id}"
  done <<<"${instance_ids}"

  aws::_cli ec2 describe-instances \
    --instance-ids "${ids[@]}" \
    --filters 'Name=instance-state-name,Values=pending,running' \
    --region "$2" --output json
}

### Write the current instance's Auto Scaling group name.
aws::auto-scaling-group-name() {
  if [[ "$#" -ne 2 ]] ||
    ! number::_is-positive-integer-at-most "$1" 2147483647 ||
    ! number::_is-positive-integer-at-most "$2" 2147483647; then
    return 64
  fi

  local instance_id=''
  local region=''
  instance_id="$(aws::instance-id)" || return "$?"
  region="$(aws::instance-region)" || return "$?"
  aws::wait-for-instance-tag \
    "${instance_id}" "${region}" 'aws:autoscaling:groupName' "$1" "$2"
}

### Write the desired capacity of an Auto Scaling group.
aws::auto-scaling-group-size() {
  if [[ "$#" -ne 2 ]] || ! aws::_require-value "$1" || ! aws::_require-value "$2"; then
    return 64
  fi

  local group=''
  command -v perl >/dev/null 2>&1 || return 69
  group="$(aws::auto-scaling-group "$1" "$2")" || return "$?"
  printf '%s' "${group}" |
    perl -MJSON::PP -0777 -e '
      my $data = eval { decode_json(<STDIN>) };
      exit 75 if $@ || ref($data) ne "HASH";
      my $size = $data->{DesiredCapacity};
      exit 75 unless defined($size) && !ref($size) && $size =~ /\A[0-9]+\z/;
      print $size, "\n";
    ' 2>/dev/null
}

arg::completion::register-all
