name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          submodules: recursive

      - name: Install ShellCheck on macOS
        if: runner.os == 'macOS'
        run: brew install shellcheck

      - name: Install ShellCheck on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --yes shellcheck

      - name: Run all checks
        run: ./bin/check
